- hosts: all
  gather_facts: yes
  tasks:
  - name: Set hostname according new_hostname variable
    shell: "hostnamectl set-hostname {{new_hostname}}"
    become: yes
    when: ( new_hostname is defined ) and ( ansible_facts['fqdn'] != new_hostname )
  
  - name: Install updates
    yum: name=* state=latest update_cache=yes
    become: yes

  - name: Install net-tools (netstat, ...)
    yum:
      name: net-tools
      state: latest

  - name: Disable and stop firewalld
    service:
      name: firewalld
      enabled: no
      state: stopped

  - name: Add IP address of all hosts to all hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_ssh_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_ssh_host is defined
    with_items: "{{ groups.all }}"
