- name: copy nginx-plus configuration file default.conf
  template: src=templates/etc/nginx/conf.d/default.conf dest=/etc/nginx/conf.d/default.conf owner=root mode=0644

- name: copy nginx-plus configuration file nginx.conf
  template: src=templates/etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf owner=root mode=0644

- name: reload nginx
  service:
    name: nginx
    state: restarted
